const teams = [
  {
    id: 1,
    team_name: 'Oracle Red Bull Racing',
    base: 'Milton Keynes, United Kingdom',
    team_chief: 'Christian Horner',
  },
  {
    id: 2,
    team_name: 'Mercedes-AMG PETRONAS F1',
    base: 'Brackley, United Kingdom',
    team_chief: 'Toto Wolff',
  },
  {
    id: 3,
    team_name: 'Aston Martin Aramco Cognizant F1',
    base: 'Silverstone, United Kingdom',
    team_chief: 'Mike Krack',
  },
  {
    id: 4,
    team_name: 'Scuderia Ferrari',
    base: 'Maranello, Italy',
    team_chief: 'Frédéric Vasseur',
  },
  {
    id: 5,
    team_name: 'BWT Alpine F1 Team',
    base: 'Enstone, United Kingdom',
    team_chief: 'Otmar Szafnauer',
  },
  {
    id: 6,
    team_name: 'McLaren F1 Team',
    base: 'Woking, United Kingdom',
    team_chief: 'Andrea Stella',
  },
  {
    id: 7,
    team_name: 'MoneyGram Haas F1 Team',
    base: 'Kannapolis, United States',
    team_chief: 'Guenther Steiner',
  },
  {
    id: 8,
    team_name: 'Alfa Romeo F1 Team Stake',
    base: 'Hinwil, Switzerland',
    team_chief: 'Alessandro Alunni Bravi',
  },
  {
    id: 9,
    team_name: 'Scuderia AlphaTauri',
    base: 'Faenza, Italy',
    team_chief: 'Franz Tost',
  },
  {
    id: 10,
    team_name: 'Williams Racing',
    base: 'Grove, United Kingdom',
    team_chief: 'James Vowles',
  },
];

const drivers = [
  {
    id: 1,
    full_name: 'Max Verstappen',
    team_id: 1,
    no: 1,
    country: 'Netherlands',
    date_of_birth: new Date('1997-09-30'),
    place_of_birth: 'Hasselt, Belgiu',
    rank: 1,
  },
  {
    id: 2,
    full_name: 'Sergio Perez',
    team_id: 1,
    no: 11,
    country: 'Mexico',
    date_of_birth: new Date('1990-01-26'),
    place_of_birth: 'Guadalajara, Mexico',
    rank: 2,
  },
  {
    id: 3,
    full_name: 'Lewis Hamilton',
    team_id: 2,
    no: 44,
    country: 'United Kingdom',
    date_of_birth: new Date('1985-01-07'),
    place_of_birth: 'Stevenage, England',
    rank: 4,
  },
  {
    id: 4,
    full_name: 'George Russell',
    team_id: 2,
    no: 63,
    country: 'United Kingdom',
    date_of_birth: new Date('1998-02-15'),
    place_of_birth: 'Kings Lynn, England',
    rank: 5,
  },
  {
    id: 5,
    full_name: 'Fernando Alonso',
    team_id: 3,
    no: 14,
    country: 'Spain',
    date_of_birth: new Date('1981-07-29'),
    place_of_birth: 'Oviedo, Spain',
    rank: 3,
  },
  {
    id: 6,
    full_name: 'Lance Stroll',
    team_id: 3,
    no: 18,
    country: 'Canada',
    date_of_birth: new Date('1998-10-29'),
    place_of_birth: 'Montreal, Canada',
    rank: 8,
  },
  {
    id: 7,
    full_name: 'Carlos Sainz',
    team_id: 4,
    no: 55,
    country: 'Spain',
    date_of_birth: new Date('1994-09-01'),
    place_of_birth: 'Madrid, Spain',
    rank: 6,
  },
  {
    id: 8,
    full_name: 'Charles Leclerc',
    team_id: 4,
    no: 16,
    country: 'Monaco',
    date_of_birth: new Date('1997-10-16'),
    place_of_birth: 'Monte Carlo, Monaco',
    rank: 7,
  },
  {
    id: 9,
    full_name: 'Esteban Ocon',
    team_id: 5,
    no: 31,
    country: 'France',
    date_of_birth: new Date('1996-09-17'),
    place_of_birth: 'Évreux, Normandy',
    rank: 9,
  },
  {
    id: 10,
    full_name: 'Pierre Gasly',
    team_id: 5,
    no: 10,
    country: 'France',
    date_of_birth: new Date('1996-02-07'),
    place_of_birth: 'Rouen, France',
    rank: 10,
  },
  {
    id: 11,
    full_name: 'Lando Norris',
    team_id: 6,
    no: 4,
    country: 'United Kingdom',
    date_of_birth: new Date('1999-11-13'),
    place_of_birth: 'Bristol, Engla',
    rank: 11,
  },
  {
    id: 12,
    full_name: 'Oscar Piastri',
    team_id: 6,
    no: 81,
    country: 'Australia',
    date_of_birth: new Date('2001-04-06'),
    place_of_birth: 'Melbourne, Victoria',
    rank: 13,
  },
  {
    id: 13,
    full_name: 'Nico Hulkenberg',
    team_id: 7,
    no: 27,
    country: 'Germany',
    date_of_birth: new Date('1987-08-19'),
    place_of_birth: 'Emmerich am Rhein, Germany',
    rank: 12,
  },
  {
    id: 14,
    full_name: 'Kevin Magnussen',
    team_id: 7,
    no: 20,
    country: 'Denmark',
    date_of_birth: new Date('1992-10-05'),
    place_of_birth: 'Roskilde, Denmark',
    rank: 17,
  },
  {
    id: 15,
    full_name: 'Valtteri Bottas',
    team_id: 8,
    no: 77,
    country: 'Finland',
    date_of_birth: new Date('1989-08-28'),
    place_of_birth: 'Nastola, Finland',
    rank: 14,
  },
  {
    id: 16,
    full_name: 'Zhou Guanyu',
    team_id: 8,
    no: 24,
    country: 'China',
    date_of_birth: new Date('1999-05-30'),
    place_of_birth: 'Shanghai, China',
    rank: 15,
  },
  {
    id: 17,
    full_name: 'Yuki Tsunoda',
    team_id: 9,
    no: 22,
    country: 'Japan',
    date_of_birth: new Date('2000-05-11'),
    place_of_birth: 'Sagamihara, Japan',
    rank: 16,
  },
  {
    id: 18,
    full_name: 'Nyck De Vries',
    team_id: 9,
    no: 21,
    country: 'Netherlands',
    date_of_birth: new Date('1995-02-06'),
    place_of_birth: 'Uitwellingerga, Netherlands',
    rank: 19,
  },
  {
    id: 19,
    full_name: 'Alexander Albon',
    team_id: 10,
    no: 23,
    country: 'Thailand',
    date_of_birth: new Date('1996-03-23'),
    place_of_birth: 'London, England',
    rank: 18,
  },
  {
    id: 20,
    full_name: 'Logan Sargeant',
    team_id: 10,
    no: 2,
    country: 'United States',
    date_of_birth: new Date('2000-12-31'),
    place_of_birth: 'Fort Lauderdale, Flori',
    rank: 20,
  },
];

const races = [
  {
    id: 1,
    grand_prix: 'Bahrain',
    race_date: new Date('2023-03-05'),
  },
  {
    id: 2,
    grand_prix: 'Saudi Arabia',
    race_date: new Date('2023-03-19'),
  },
  {
    id: 3,
    grand_prix: 'Australia',
    race_date: new Date('2023-04-30'),
  },
  {
    id: 4,
    grand_prix: 'Azerbaijan',
    race_date: new Date('2023-04-30'),
  },
  {
    id: 5,
    grand_prix: 'Miami',
    race_date: new Date('2023-05-07'),
  },
  {
    id: 6,
    grand_prix: 'Monaco',
    race_date: new Date('2023-05-28'),
  },
  {
    id: 7,
    grand_prix: 'Spain',
    race_date: new Date('2023-06-04'),
  },
  {
    id: 8,
    grand_prix: 'Monaco',
    race_date: new Date('2023-05-28'),
  },
  {
    id: 9,
    grand_prix: 'Bahrain',
    race_date: new Date('2022-03-20'),
  },
  {
    id: 10,
    grand_prix: 'Saudi Arabia',
    race_date: new Date('2022-03-27'),
  },
  {
    id: 11,
    grand_prix: 'Australia',
    race_date: new Date('2022-04-10'),
  },
  {
    id: 12,
    grand_prix: 'Emilia Romagna',
    race_date: new Date('2022-04-24'),
  },
  {
    id: 13,
    grand_prix: 'Miami',
    race_date: new Date('2022-05-08'),
  },
  {
    id: 14,
    grand_prix: 'Spain',
    race_date: new Date('2022-05-22'),
  },
  {
    id: 15,
    grand_prix: 'Monaco',
    race_date: new Date('2022-05-29'),
  },
  {
    id: 16,
    grand_prix: 'Azerbaijan',
    race_date: new Date('2022-06-12'),
  },
  {
    id: 17,
    grand_prix: 'Canada',
    race_date: new Date('2022-06-19'),
  },
  {
    id: 18,
    grand_prix: 'Great Britain',
    race_date: new Date('2022-07-03'),
  },
  {
    id: 19,
    grand_prix: 'Austria',
    race_date: new Date('2022-07-10'),
  },
  {
    id: 20,
    grand_prix: 'France',
    race_date: new Date('2022-07-24'),
  },
  {
    id: 21,
    grand_prix: 'Hungary',
    race_date: new Date('2022-07-31'),
  },
  {
    id: 22,
    grand_prix: 'Belgium',
    race_date: new Date('2022-08-28'),
  },
  {
    id: 23,
    grand_prix: 'Netherlands',
    race_date: new Date('2022-09-04'),
  },
  {
    id: 24,
    grand_prix: 'Italy',
    race_date: new Date('2022-09-11'),
  },
  {
    id: 25,
    grand_prix: 'Singapore',
    race_date: new Date('2022-10-02'),
  },
  {
    id: 26,
    grand_prix: 'Japan',
    race_date: new Date('2022-10-09'),
  },
  {
    id: 27,
    grand_prix: 'United States',
    race_date: new Date('2022-10-23'),
  },
  {
    id: 28,
    grand_prix: 'Mexico',
    race_date: new Date('2022-10-30'),
  },
  {
    id: 29,
    grand_prix: 'Brazil',
    race_date: new Date('2022-11-13'),
  },
  {
    id: 30,
    grand_prix: 'Abu Dhabi',
    race_date: new Date('2022-11-20'),
  },
];

const raceResults = [
  {
    race_id: 1,
    pos: 1,
    driver_id: 1,
    car: 'RED BULL RACING HONDA RBPT',
    laps: 57,
    time: '5636740',
    pts: 25,
  },
  {
    race_id: 1,
    pos: 2,
    driver_id: 2,
    car: 'RED BULL RACING HONDA RBPT',
    laps: 57,
    time: '5648727',
    pts: 18,
  },
  {
    race_id: 1,
    pos: 3,
    driver_id: 5,
    car: 'ASTON MARTIN ARAMCO MERCEDES',
    laps: 57,
    time: '5636740',
    pts: 15,
  },
  {
    race_id: 1,
    pos: 4,
    driver_id: 7,
    car: 'FERRARI',
    laps: 57,
    time: '5684792',
    pts: 12,
  },
  {
    race_id: 1,
    pos: 5,
    driver_id: 3,
    car: 'MERCEDES',
    laps: 57,
    time: '5687717',
    pts: 10,
  },
  {
    race_id: 1,
    pos: 6,
    driver_id: 6,
    car: 'ASTON MARTIN ARAMCO MERCEDES',
    laps: 57,
    time: '5691242',
    pts: 8,
  },
  {
    race_id: 1,
    pos: 7,
    driver_id: 4,
    car: 'MERCEDES',
    laps: 57,
    time: '5692613',
    pts: 6,
  },
  {
    race_id: 1,
    pos: 8,
    driver_id: 15,
    car: 'ALFA ROMEO FERRARI',
    laps: 57,
    time: '5709387',
    pts: 4,
  },
  {
    race_id: 1,
    pos: 9,
    driver_id: 10,
    car: 'ALPINE RENAULT',
    laps: 57,
    time: '5710493',
    pts: 2,
  },
  {
    race_id: 1,
    pos: 10,
    driver_id: 19,
    car: 'WILLIAMS MERCEDES',
    laps: 57,
    time: '5726514',
    pts: 1,
  },
  {
    race_id: 1,
    pos: 11,
    driver_id: 17,
    car: 'ALPHATAURI HONDA RBPT',
    laps: 57,
    time: '5727610',
    pts: 0,
  },
  {
    race_id: 1,
    pos: 12,
    driver_id: 20,
    car: 'WILLIAMS MERCEDES',
    laps: 56,
    time: '0',
    pts: 0,
  },
  {
    race_id: 1,
    pos: 13,
    driver_id: 14,
    car: 'HAAS FERRARI',
    laps: 56,
    time: '0',
    pts: 0,
  },
  {
    race_id: 1,
    pos: 14,
    driver_id: 18,
    car: 'ALPHATAURI HONDA RBPT',
    laps: 56,
    time: '0',
    pts: 0,
  },
  {
    race_id: 1,
    pos: 15,
    driver_id: 13,
    car: 'HAAS FERRARI',
    laps: 56,
    time: '0',
    pts: 0,
  },
  {
    race_id: 1,
    pos: 16,
    driver_id: 16,
    car: 'ALFA ROMEO FERRARI',
    laps: 56,
    time: '0',
    pts: 0,
  },
  {
    race_id: 1,
    pos: 17,
    driver_id: 11,
    car: 'MCLAREN MERCEDES',
    laps: 55,
    time: '0',
    pts: 0,
  },
  {
    race_id: 1,
    pos: 0,
    driver_id: 9,
    car: 'ALPINE RENAULT',
    laps: 41,
    time: '0',
    pts: 0,
  },
  {
    race_id: 1,
    pos: 0,
    driver_id: 8,
    car: 'FERRARI',
    laps: 39,
    time: '0',
    pts: 0,
  },
  {
    race_id: 1,
    pos: 0,
    driver_id: 12,
    car: 'MCLAREN MERCEDES',
    laps: 13,
    time: '0',
    pts: 0,
  },
  {
    race_id: 5,
    pos: 1,
    driver_id: 1,
    car: 'RED BULL RACING HONDA RBPT',
    laps: 57,
    time: '5258240',
    pts: 26,
  },
  {
    race_id: 5,
    pos: 2,
    driver_id: 2,
    car: 'RED BULL RACING HONDA RBPT',
    laps: 57,
    time: '5263624',
    pts: 18,
  },
  {
    race_id: 5,
    pos: 3,
    driver_id: 5,
    car: 'ASTON MARTIN ARAMCO MERCEDES',
    laps: 57,
    time: '5284545',
    pts: 15,
  },
  {
    race_id: 5,
    pos: 4,
    driver_id: 4,
    car: 'MERCEDES',
    laps: 57,
    time: '5291469',
    pts: 12,
  },
  {
    race_id: 5,
    pos: 5,
    driver_id: 7,
    car: 'FERRARI',
    laps: 57,
    time: '5300751',
    pts: 10,
  },
  {
    race_id: 5,
    pos: 6,
    driver_id: 3,
    car: 'MERCEDES',
    laps: 57,
    time: '5309489',
    pts: 8,
  },
  {
    race_id: 5,
    pos: 7,
    driver_id: 8,
    car: 'FERRARI',
    laps: 57,
    time: '5311228',
    pts: 6,
  },
  {
    race_id: 5,
    pos: 8,
    driver_id: 10,
    car: 'ALPINE RENAULT',
    laps: 57,
    time: '5313910',
    pts: 4,
  },
  {
    race_id: 5,
    pos: 9,
    driver_id: 9,
    car: 'ALPINE RENAULT',
    laps: 57,
    time: '5316363',
    pts: 2,
  },
  {
    race_id: 5,
    pos: 10,
    driver_id: 14,
    car: 'HAAS FERRARI',
    laps: 57,
    time: '5321185',
    pts: 1,
  },
  {
    race_id: 5,
    pos: 11,
    driver_id: 17,
    car: 'ALPHATAURI HONDA RBPT',
    laps: 57,
    time: '5322549',
    pts: 0,
  },
  {
    race_id: 5,
    pos: 12,
    driver_id: 6,
    car: 'ASTON MARTIN ARAMCO MERCEDES',
    laps: 57,
    time: '5322994',
    pts: 0,
  },
  {
    race_id: 5,
    pos: 13,
    driver_id: 15,
    car: 'ALFA ROMEO FERRARI',
    laps: 57,
    time: '5329877',
    pts: 0,
  },
  {
    race_id: 5,
    pos: 14,
    driver_id: 19,
    car: 'WILLIAMS MERCEDES',
    laps: 57,
    time: '5331101',
    pts: 0,
  },
  {
    race_id: 5,
    pos: 15,
    driver_id: 13,
    car: 'HAAS FERRARI',
    laps: 57,
    time: '5333190',
    pts: 0,
  },
  {
    race_id: 5,
    pos: 16,
    driver_id: 16,
    car: 'ALFA ROMEO FERRARI',
    laps: 57,
    time: '5336680',
    pts: 0,
  },
  {
    race_id: 5,
    pos: 17,
    driver_id: 11,
    car: 'MCLAREN MERCEDES',
    laps: 57,
    time: '5345957',
    pts: 0,
  },
  {
    race_id: 5,
    pos: 18,
    driver_id: 18,
    car: 'ALPHATAURI HONDA RBPT',
    laps: 57,
    time: '5347189',
    pts: 0,
  },
  {
    race_id: 5,
    pos: 19,
    driver_id: 12,
    car: 'MCLAREN MERCEDES',
    laps: 56,
    time: '0',
    pts: 0,
  },
  {
    race_id: 5,
    pos: 20,
    driver_id: 20,
    car: 'WILLIAMS MERCEDES',
    laps: 56,
    time: '0',
    pts: 0,
  },
  {
    race_id: 14,
    pos: 1,
    driver_id: 1,
    car: 'RED BULL RACING RBPT',
    laps: 66,
    time: '5840480',
    pts: 25,
  },
  {
    race_id: 14,
    pos: 2,
    driver_id: 2,
    car: 'RED BULL RACING RBPT',
    laps: 66,
    time: '5853552',
    pts: 19,
  },
  {
    race_id: 14,
    pos: 3,
    driver_id: 4,
    car: 'MERCEDES',
    laps: 66,
    time: '5873407',
    pts: 15,
  },
  {
    race_id: 14,
    pos: 4,
    driver_id: 7,
    car: 'FERRARI',
    laps: 66,
    time: '5885688',
    pts: 12,
  },
  {
    race_id: 14,
    pos: 5,
    driver_id: 3,
    car: 'MERCEDES',
    laps: 66,
    time: '5895014',
    pts: 10,
  },
  {
    race_id: 14,
    pos: 6,
    driver_id: 15,
    car: 'ALFA ROMEO FERRARI',
    laps: 66,
    time: '5900456',
    pts: 8,
  },
  {
    race_id: 14,
    pos: 7,
    driver_id: 9,
    car: 'ALPINE RENAULT',
    laps: 66,
    time: '5915877',
    pts: 6,
  },
  {
    race_id: 14,
    pos: 8,
    driver_id: 11,
    car: 'MCLAREN MERCEDES',
    laps: 66,
    time: '592371',
    pts: 4,
  },
  {
    race_id: 14,
    pos: 9,
    driver_id: 5,
    car: 'ALPINE RENAULT',
    laps: 65,
    time: '0',
    pts: 2,
  },
  {
    race_id: 14,
    pos: 10,
    driver_id: 17,
    car: 'ALPHATAURI RBPT',
    laps: 65,
    time: '0',
    pts: 1,
  },
  {
    race_id: 14,
    pos: 11,
    driver_id: 5,
    car: 'ASTON MARTIN ARAMCO MERCEDES',
    laps: 65,
    time: '0',
    pts: 0,
  },
  {
    race_id: 14,
    pos: 12,
    driver_id: 11,
    car: 'MCLAREN MERCEDES',
    laps: 65,
    time: '0',
    pts: 0,
  },
  {
    race_id: 14,
    pos: 13,
    driver_id: 10,
    car: 'ALPHATAURI RBPT',
    laps: 65,
    time: '0',
    pts: 0,
  },
  {
    race_id: 14,
    pos: 14,
    driver_id: 13,
    car: 'HAAS FERRARI',
    laps: 65,
    time: '0',
    pts: 0,
  },
  {
    race_id: 14,
    pos: 15,
    driver_id: 6,
    car: 'ASTON MARTIN ARAMCO MERCEDES',
    laps: 65,
    time: '0',
    pts: 0,
  },
  {
    race_id: 14,
    pos: 16,
    driver_id: 20,
    car: 'WILLIAMS MERCEDES',
    laps: 64,
    time: '0',
    pts: 0,
  },
  {
    race_id: 14,
    pos: 17,
    driver_id: 14,
    car: 'HAAS FERRARI',
    laps: 64,
    time: '0',
    pts: 0,
  },
  {
    race_id: 14,
    pos: 18,
    driver_id: 19,
    car: 'WILLIAMS MERCEDES',
    laps: 64,
    time: '0',
    pts: 0,
  },
  {
    race_id: 14,
    pos: 0,
    driver_id: 16,
    car: 'ALFA ROMEO FERRARI',
    laps: 28,
    time: '0',
    pts: 0,
  },
  {
    race_id: 14,
    pos: 0,
    driver_id: 8,
    car: 'FERRARI',
    laps: 27,
    time: '0',
    pts: 0,
  },
];

export { teams, drivers, races, raceResults };
